# Generated by Django 6.0.5 on 2026-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamarmita',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='marmita',
            name='tamanho',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequena'), ('M', 'Média'), ('G', 'Grande')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
