# Generated by Django 6.0.5 on 2026-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marmita',
            name='refrigerante',
            field=models.BooleanField(default=False, verbose_name='Inclui Refrigerante?'),
        ),
    ]
