# Generated by Django 5.0 on 2026-06-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoriamarmita_id_alter_itempedido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix (QrCode / Chave)'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('DINHEIRO', 'Dinheiro')], default='PIX', max_length=20),
        ),
    ]
